#=============================================================================
# Project settings
#=============================================================================
# Only build master; do not build every branch.
branches:
  only:
    - master

#=============================================================================
# Environment
#=============================================================================
# Use new Travis infrastructure


#=============================================================================
# Build matrix
#   - Note that we should not use osx_image otherwise brew will fail.
#     This is because mpich depends on gcc and installation of gcc fails
#     with brew link.
#=============================================================================
matrix:
  fast_finish: true
  include:
    - language: cpp
      os: linux
      dist: trusty
      sudo: true
      env: [ MPI=mpich]
    - language: cpp
      os: osx
      sudo: false
      env: [ MPI=mpich]
    - language: cpp
      os: linux
      dist: trusty
      sudo: true
      env: [ MPI=openmpi]
    - language: cpp
      os: osx
      sudo: false
      env: [ MPI=openmpi]


#=============================================================================
# Build matrix
#=============================================================================
env:
  global:
    - MPI_IMPL=$MPI
    - SPACK_ROOT=$TRAVIS_BUILD_DIR/spack
    - PATH=$SPACK_ROOT/bin:$PATH
    - MODULEPATH

# Common packages for devlopment build
addons:
  apt:
    packages:
      - build-essential
      - automake
      - cmake
      - bison
      - flex
      - pkg-config
      - autoconf
      - automake
      - make
      - libncurses-dev
      - environment-modules

# Work around Travis's lack of support for Python on OSX
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions python > /dev/null || brew install python; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gcc    > /dev/null || brew install gcc;    fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gnupg2 > /dev/null || brew install gnupg2; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - sh .travis.mpi-install.sh $MPI_IMPL

# Install various dependencies
install:
  - pip install --upgrade pip
#  - pip install --upgrade six
#  - pip install --upgrade setuptools
#  - pip install --upgrade codecov
#  - pip install --upgrade flake8
#  - if [[ "$TEST_SUITE" == "doc" ]]; then pip install --upgrade -r lib/spack/docs/requirements.txt; fi

before_script:
  # Need this for the git tests to succeed.
  - export PATH=$SPACK_ROOT/bin:$PATH
  - ./.travis.spack_setup.sh
  - echo $MODULEPATH

#=============================================================================
# Building
#=============================================================================
script:

  - echo "------- SPACK CONFIGURATIONS -------"
  - spack compilers
  - spack config get packages
  - echo "------------------------------------"

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "-->LINUX"; source /etc/profile.d/modules.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "-->OSX"; source /usr/local/opt/modules/Modules/init/bash; fi
  - source $SPACK_ROOT/share/spack/setup-env.sh

  - spack spec coreneuron
  - spack install mod2c
  - spack install coreneuron ~neurodamusmod ~report
  - spack install neuron@master
  - spack find -v
  - echo $MODULEPATH
  - spack load mod2c

#after_success:
#  - codecov --env PY_VERSION

#=============================================================================
# Notifications
#=============================================================================
notifications:
  email:
    recipients: pramod.s.kumbhar@gmail.com
    on_success: change
    on_failure: always
