#=============================================================================
# Project settings
#=============================================================================
# Only build master; do not build every branch.
branches:
  only:
    - master

#=============================================================================
# Build matrix
#=============================================================================
matrix:
  fast_finish: true
  include:
    - language: c
      os: linux
      dist: trusty
      env: [ TEST_SUITE=unit, COVERAGE=true ]

#=============================================================================
# Build matrix
#=============================================================================
env:
  global:
    - MPI_IMPL=mpich
    - SPACK_ROOT=$TRAVIS_BUILD_DIR/spack
    - PATH=$SPACK_ROOT/bin:$PATH
    - MODULEPATH

#=============================================================================
# Environment
#=============================================================================
# Use new Travis infrastructure
sudo: true

# Common packages for devlopment build
addons:
  apt:
    packages:
      - build-essential
      - automake
      - cmake
      - bison
      - flex
      - pkg-config
      - autoconf
      - automake
      - make
      - python2.7-dev
      - libncurses-dev
      - environment-modules

# Work around Travis's lack of support for Python on OSX
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions python > /dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gcc    > /dev/null || brew install gcc;    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew ls --versions gnupg2 > /dev/null || brew install gnupg2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - sh .travis.mpi-install.sh $MPI_IMPL

# Install various dependencies
install:
  - pip install --upgrade pip
#  - pip install --upgrade six
#  - pip install --upgrade setuptools
#  - pip install --upgrade codecov
#  - pip install --upgrade flake8
#  - if [[ "$TEST_SUITE" == "doc" ]]; then pip install --upgrade -r lib/spack/docs/requirements.txt; fi

before_script:
  # Need this for the git tests to succeed.
  - export PATH=$SPACK_ROOT/bin:$PATH
  - ./.travis.spack_setup.sh
  - source /etc/profile.d/modules.sh
  - source $SPACK_ROOT/share/spack/setup-env.sh
  - echo $MODULEPATH
  - env | grep MODULE
  - sudo pip install --upgrade virtualenv

#=============================================================================
# Building
#=============================================================================
script:

  - echo "------- SPACK CONFIGURATIONS -------"
  - spack compilers
  - spack config get packages
  - echo "------------------------------------"

  - spack spec coreneuron
  - spack install coreneuron ~neurodamusmod ~report
  - spack install -v neuron@master
  - spack find -v
  - echo $MODULEPATH
  - spack load coreneuron

#after_success:
#  - codecov --env PY_VERSION

#=============================================================================
# Notifications
#=============================================================================
notifications:
  email:
    recipients: pramod.s.kumbhar@gmail.com
    on_success: change
    on_failure: always
