config:
  install_tree: /gpfs/bbp.cscs.ch/project/proj16/$user/SPACK_INSTALL/viz/simulation/install
  module_roots:
    tcl: /gpfs/bbp.cscs.ch/project/proj16/$user/SPACK_INSTALL/viz/simulation/modules
