packages:

    mpich:
        paths:
            mpich@3.0.4: /usr/local
        version: [3.0.4]
        buildable: False
    openmpi:
        paths:
            openmpi@2.1.1: /usr/local
        buildable: False
        version: [2.1.1]
    cmake:
        paths:
            cmake@3.6.2: /usr/local
        version: [3.6.2]
        buildable: False
    autoconf:
        paths:
            autoconf@system: /usr/local
        buildable: False
        version: [system]
    automake:
        paths:
            automake@system: /usr/local
        buildable: False
        version: [system]
    pkg-config:
        paths:
            pkg-config@0.29.2: /usr/local
        buildable: False
        version: [0.29.2]
    libtool:
        paths:
            libtool@system: /usr/local
        buildable: False
        version: [system]
    python:
        paths:
            python@2.7: /System/Library/Frameworks/Python.framework/Versions/2.7
            python@3.6.2: /usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib
        version: [2.7, 3.6.2]
        buildable: False
    gsl:
        paths:
            gsl@2.4: /usr/local
        buildable: False
        version: [2.4]
    tau:
        variants: ~openmp ~comm ~phase
    coreneuron:
        variants: ~openmp

    all:
        compiler: [clang]
        providers:
            mpi: [mpich]
