config:
  install_tree: ~/spack_home/install/bgq/
  module_roots:
    tcl: ~/spack_home/install/bgq/tcl/
    lmod: ~/spack_home/install/bgq/lmod/
  build_stage:
    - $tempdir
    - $spack/var/spack/stage
  install_path_scheme: '${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:8}'
